# Generated by Django 6.0.7 on 2026-09-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_bbbserver_disable_ssl_janusserver_disable_ssl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='limit_products',
            field=models.ManyToManyField(blank=True, help_text='If set, the voucher only applies to these products (any variation unless a variation is listed).', related_name='limiting_vouchers', to='base.product', verbose_name='Limited products'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='limit_variations',
            field=models.ManyToManyField(blank=True, help_text='If set, the voucher only applies to these specific product variations.', related_name='limiting_vouchers', to='base.productvariation', verbose_name='Limited variations'),
        ),
    ]
