# Generated by Django 6.0.7 on 2026-09-20 04:49

from django.db import migrations
from django_scopes import scope


def add_default_speaker_questions(apps, schema_editor):
    Event = apps.get_model('base', 'Event')
    TalkQuestion = apps.get_model('base', 'TalkQuestion')

    defaults = [
        ('speaker_job_title', 'Job Title', 0),
        ('speaker_organization', 'Organization', 1),
    ]

    for event in Event.objects.all().only('id', 'slug'):
        with scope(event=event):
            for import_key, question_text, position in defaults:
                TalkQuestion.objects.get_or_create(
                    event=event,
                    import_key=import_key,
                    target='speaker',
                    defaults={
                        'question': question_text,
                        'variant': 'string',
                        'is_public': False,
                        'position': position,
                        'active': True,
                    },
                )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_voucher_limit_products'),
    ]

    operations = [
        migrations.RunPython(
            add_default_speaker_questions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
