# Generated by Django 4.2.5 on 2026-09-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_revert_default_speaker_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='admission_validity_mode',
            field=models.CharField(
                blank=True,
                choices=[('inherit', 'Same as product'), ('', 'No check-in time restriction'), ('fixed', 'Fixed start and end'), ('subevent', 'Valid during assigned event date'), ('event', 'Valid during entire event')],
                default='inherit',
                help_text='How check-in validity is determined for tickets of this variation. Use "Same as product" to inherit the product mode and overlay only the variation fields you set. Choose "No check-in time restriction" to explicitly clear a product-level restriction for this variation.',
                max_length=20,
                verbose_name='Admission validity mode'
            ),
        ),
    ]
