name: Docker PR Build

on:
  pull_request:
    branches: [development, master]

jobs:
  build_docker_image:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Build Docker image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc
        with:
          context: .
          push: false
          tags: eventyay-ticket:${{ github.sha }}
          build-args: GITHUB_TOKEN=${{ secrets.EVENTYAY_TOKEN }}
